#include "PORT.h"

Port_ConfigType Port_Configuration = {

  /**           RED LED CONFIG           **/
  portConf_LED1_CHANNEL_PORT_NUMBER, portConf_LED1_CHANNEL_CHANNEL_NUMBER,
  portConf_LED1_CHANNEL_CHANNEL_DIRECTION, portConf_LED1_CHANNEL_INPUT_PIN_MODE,
  portConf_LED1_CHANNEL_OUTPUT_PIN_MODE, portConf_LED1_CHANNEL_Mode,
  
  /**           BLUE LED CONFIG           **/
  portConf_LED2_CHANNEL_PORT_NUMBER, portConf_LED2_CHANNEL_CHANNEL_NUMBER,
  portConf_LED2_CHANNEL_CHANNEL_DIRECTION, portConf_LED2_CHANNEL_INPUT_PIN_MODE,
  portConf_LED2_CHANNEL_OUTPUT_PIN_MODE, portConf_LED2_CHANNEL_Mode,
  
  /**           GREEN LED CONFIG        **/
  portConf_LED3_CHANNEL_PORT_NUMBER, portConf_LED3_CHANNEL_CHANNEL_NUMBER,
  portConf_LED3_CHANNEL_CHANNEL_DIRECTION, portConf_LED3_CHANNEL_INPUT_PIN_MODE,
  portConf_LED3_CHANNEL_OUTPUT_PIN_MODE, portConf_LED3_CHANNEL_Mode,
  /**           SW1 CONFIG              **/
  portConf_SW1_CHANNEL_PORT_NUMBER, portConf_SW1_CHANNEL_CHANNEL_NUMBER,
  portConf_SW1_CHANNEL_CHANNEL_DIRECTION, portConf_SW1_CHANNEL_INPUT_PIN_MODE,
  portConf_SW1_CHANNEL_OUTPUT_PIN_MODE, portConf_SW1_CHANNEL_Mode,
  
  /**           SW2 CONFIG              **/
  portConf_SW2_CHANNEL_PORT_NUMBER, portConf_SW2_CHANNEL_CHANNEL_NUMBER,
  portConf_SW2_CHANNEL_CHANNEL_DIRECTION, portConf_SW2_CHANNEL_INPUT_PIN_MODE,
  portConf_SW2_CHANNEL_OUTPUT_PIN_MODE, portConf_SW2_CHANNEL_Mode,
};